// Code generated by protoc-gen-go.
// source: protobuf/data/cmdsafe.proto
// DO NOT EDIT!

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	protobuf/data/cmdsafe.proto

It has these top-level messages:
	Config
	ScryptConfig
	Command
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Hash   []byte        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Scrypt *ScryptConfig `protobuf:"bytes,2,opt,name=scrypt" json:"scrypt,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Config) GetScrypt() *ScryptConfig {
	if m != nil {
		return m.Scrypt
	}
	return nil
}

type ScryptConfig struct {
	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	N    int64  `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	R    int32  `protobuf:"varint,3,opt,name=r" json:"r,omitempty"`
	P    int32  `protobuf:"varint,4,opt,name=p" json:"p,omitempty"`
}

func (m *ScryptConfig) Reset()                    { *m = ScryptConfig{} }
func (m *ScryptConfig) String() string            { return proto.CompactTextString(m) }
func (*ScryptConfig) ProtoMessage()               {}
func (*ScryptConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScryptConfig) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ScryptConfig) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *ScryptConfig) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *ScryptConfig) GetP() int32 {
	if m != nil {
		return m.P
	}
	return 0
}

type Command struct {
	Name string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Args []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "cmdsafe.Config")
	proto.RegisterType((*ScryptConfig)(nil), "cmdsafe.ScryptConfig")
	proto.RegisterType((*Command)(nil), "cmdsafe.Command")
}

func init() { proto.RegisterFile("protobuf/data/cmdsafe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0x47, 0x49, 0x5b, 0x53, 0x8c, 0x9d, 0x02, 0x42, 0xc0, 0x25, 0x74, 0xea, 0x62, 0x8b, 0xfa,
	0x0d, 0xec, 0xa8, 0x53, 0xdc, 0xdc, 0x6e, 0xff, 0x0b, 0xe6, 0x0f, 0x49, 0xde, 0xf0, 0xbe, 0xfd,
	0xe3, 0xa6, 0x2d, 0xbc, 0xed, 0x77, 0x0e, 0xc9, 0x81, 0xcb, 0x5e, 0x9c, 0xb7, 0xd1, 0x0e, 0x97,
	0xa5, 0x9b, 0x20, 0x42, 0x37, 0xea, 0x29, 0xc0, 0x32, 0xb7, 0xc9, 0xf2, 0xf2, 0xc0, 0xfa, 0x8b,
	0xd1, 0xde, 0x9a, 0xe5, 0x6f, 0xe5, 0x9c, 0x15, 0x1b, 0x84, 0x4d, 0x10, 0x49, 0x9a, 0x4a, 0xa5,
	0xcd, 0x5f, 0x19, 0x0d, 0xa3, 0xbf, 0xba, 0x28, 0x32, 0x49, 0x9a, 0xa7, 0xf7, 0xe7, 0xf6, 0xcc,
	0xfc, 0x24, 0xbd, 0x7f, 0x55, 0xc7, 0xa3, 0xfa, 0x9b, 0x55, 0xf7, 0x1e, 0x93, 0x01, 0xfe, 0xe3,
	0x99, 0xc4, 0xcd, 0x2b, 0x46, 0x4c, 0xaa, 0xe5, 0x8a, 0x18, 0x24, 0x2f, 0x72, 0x49, 0x9a, 0x07,
	0x45, 0x3c, 0x92, 0x13, 0xc5, 0x4e, 0xae, 0x7e, 0x63, 0x65, 0x6f, 0xb5, 0x06, 0x33, 0x61, 0xc8,
	0x80, 0x9e, 0x53, 0xe8, 0x51, 0xa5, 0x8d, 0x0e, 0xfc, 0x1a, 0x44, 0x26, 0x73, 0x74, 0xb8, 0x3f,
	0xe9, 0x6f, 0x81, 0xc7, 0x0e, 0x34, 0x5d, 0xf9, 0x71, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x07, 0x8d,
	0x63, 0x0d, 0x04, 0x01, 0x00, 0x00,
}
