// Code generated by protoc-gen-go.
// source: protobuf/cmdsafe/cmdsafe.proto
// DO NOT EDIT!

/*
Package cmdsafe is a generated protocol buffer package.

It is generated from these files:
	protobuf/cmdsafe/cmdsafe.proto

It has these top-level messages:
	Command
*/
package cmdsafe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Name       string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Executable string   `protobuf:"bytes,2,opt,name=executable" json:"executable,omitempty"`
	Args       []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetExecutable() string {
	if m != nil {
		return m.Executable
	}
	return ""
}

func (m *Command) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Command)(nil), "cmdsafe.Command")
}

func init() { proto.RegisterFile("protobuf/cmdsafe/cmdsafe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xce, 0x4d, 0x29, 0x4e, 0x4c, 0x4b, 0x85, 0xd1, 0x7a, 0x60,
	0x09, 0x21, 0x76, 0x28, 0x57, 0x29, 0x90, 0x8b, 0xdd, 0x39, 0x3f, 0x37, 0x37, 0x31, 0x2f, 0x45,
	0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc,
	0x16, 0x92, 0xe3, 0xe2, 0x4a, 0xad, 0x48, 0x4d, 0x2e, 0x2d, 0x49, 0x4c, 0xca, 0x49, 0x95, 0x60,
	0x02, 0xcb, 0x20, 0x89, 0x80, 0xf4, 0x24, 0x16, 0xa5, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x83, 0xf4,
	0x80, 0xd8, 0x4e, 0x9c, 0x51, 0x30, 0xd3, 0x93, 0xd8, 0xc0, 0xb6, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x4f, 0xd0, 0x58, 0x14, 0x8f, 0x00, 0x00, 0x00,
}
