// Code generated by protoc-gen-go.
// source: protobuf/crypto/crypto.proto
// DO NOT EDIT!

/*
Package crypto is a generated protocol buffer package.

It is generated from these files:
	protobuf/crypto/crypto.proto

It has these top-level messages:
	UserKey
	ScryptConfig
	CryptoEnvelope
*/
package crypto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Supported key derivation algorithms.
type KeyAlgo int32

const (
	KeyAlgo_SCRYPT KeyAlgo = 0
)

var KeyAlgo_name = map[int32]string{
	0: "SCRYPT",
}
var KeyAlgo_value = map[string]int32{
	"SCRYPT": 0,
}

func (x KeyAlgo) String() string {
	return proto.EnumName(KeyAlgo_name, int32(x))
}
func (KeyAlgo) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Supported encryption algorithms.
type CipherAlgo int32

const (
	CipherAlgo_AES256CTR CipherAlgo = 0
)

var CipherAlgo_name = map[int32]string{
	0: "AES256CTR",
}
var CipherAlgo_value = map[string]int32{
	"AES256CTR": 0,
}

func (x CipherAlgo) String() string {
	return proto.EnumName(CipherAlgo_name, int32(x))
}
func (CipherAlgo) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The password key derivation configuration.
type UserKey struct {
	Hash      []byte        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Algorithm KeyAlgo       `protobuf:"varint,2,opt,name=algorithm,enum=cmdsafe.KeyAlgo" json:"algorithm,omitempty"`
	Scrypt    *ScryptConfig `protobuf:"bytes,3,opt,name=scrypt" json:"scrypt,omitempty"`
}

func (m *UserKey) Reset()                    { *m = UserKey{} }
func (m *UserKey) String() string            { return proto.CompactTextString(m) }
func (*UserKey) ProtoMessage()               {}
func (*UserKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserKey) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *UserKey) GetAlgorithm() KeyAlgo {
	if m != nil {
		return m.Algorithm
	}
	return KeyAlgo_SCRYPT
}

func (m *UserKey) GetScrypt() *ScryptConfig {
	if m != nil {
		return m.Scrypt
	}
	return nil
}

type ScryptConfig struct {
	Salt []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	N    int64  `protobuf:"varint,2,opt,name=n" json:"n,omitempty"`
	R    int32  `protobuf:"varint,3,opt,name=r" json:"r,omitempty"`
	P    int32  `protobuf:"varint,4,opt,name=p" json:"p,omitempty"`
}

func (m *ScryptConfig) Reset()                    { *m = ScryptConfig{} }
func (m *ScryptConfig) String() string            { return proto.CompactTextString(m) }
func (*ScryptConfig) ProtoMessage()               {}
func (*ScryptConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScryptConfig) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *ScryptConfig) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *ScryptConfig) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *ScryptConfig) GetP() int32 {
	if m != nil {
		return m.P
	}
	return 0
}

type CryptoEnvelope struct {
	Hmac      []byte     `protobuf:"bytes,1,opt,name=hmac,proto3" json:"hmac,omitempty"`
	Iv        []byte     `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	Key       []byte     `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Algorithm CipherAlgo `protobuf:"varint,4,opt,name=algorithm,enum=cmdsafe.CipherAlgo" json:"algorithm,omitempty"`
	UserKey   *UserKey   `protobuf:"bytes,5,opt,name=user_key,json=userKey" json:"user_key,omitempty"`
	Data      []byte     `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CryptoEnvelope) Reset()                    { *m = CryptoEnvelope{} }
func (m *CryptoEnvelope) String() string            { return proto.CompactTextString(m) }
func (*CryptoEnvelope) ProtoMessage()               {}
func (*CryptoEnvelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CryptoEnvelope) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

func (m *CryptoEnvelope) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

func (m *CryptoEnvelope) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CryptoEnvelope) GetAlgorithm() CipherAlgo {
	if m != nil {
		return m.Algorithm
	}
	return CipherAlgo_AES256CTR
}

func (m *CryptoEnvelope) GetUserKey() *UserKey {
	if m != nil {
		return m.UserKey
	}
	return nil
}

func (m *CryptoEnvelope) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserKey)(nil), "cmdsafe.UserKey")
	proto.RegisterType((*ScryptConfig)(nil), "cmdsafe.ScryptConfig")
	proto.RegisterType((*CryptoEnvelope)(nil), "cmdsafe.CryptoEnvelope")
	proto.RegisterEnum("cmdsafe.KeyAlgo", KeyAlgo_name, KeyAlgo_value)
	proto.RegisterEnum("cmdsafe.CipherAlgo", CipherAlgo_name, CipherAlgo_value)
}

func init() { proto.RegisterFile("protobuf/crypto/crypto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x6b, 0xf2, 0x40,
	0x10, 0xc6, 0x5d, 0xff, 0x24, 0x3a, 0x6f, 0x5e, 0x09, 0x5b, 0x84, 0x40, 0x7b, 0x10, 0x4f, 0x62,
	0x69, 0x4a, 0x2d, 0xed, 0xdd, 0x06, 0x4f, 0xf6, 0x50, 0x56, 0x7b, 0x68, 0x2f, 0x65, 0x8d, 0xab,
	0x09, 0x4d, 0xb2, 0x61, 0x37, 0x0a, 0x81, 0x7e, 0xb2, 0x7e, 0xba, 0xb2, 0x63, 0x6a, 0xa4, 0xa7,
	0x3c, 0x33, 0x4c, 0x9e, 0x99, 0xdf, 0xb3, 0x70, 0x95, 0x2b, 0x59, 0xc8, 0xf5, 0x7e, 0x7b, 0x1b,
	0xaa, 0x32, 0x2f, 0x64, 0xf5, 0xf1, 0xb1, 0x4d, 0xed, 0x30, 0xdd, 0x68, 0xbe, 0x15, 0xa3, 0x2f,
	0xb0, 0x5f, 0xb5, 0x50, 0x0b, 0x51, 0x52, 0x0a, 0xed, 0x88, 0xeb, 0xc8, 0x23, 0x43, 0x32, 0x76,
	0x18, 0x6a, 0xea, 0x43, 0x8f, 0x27, 0x3b, 0xa9, 0xe2, 0x22, 0x4a, 0xbd, 0xe6, 0x90, 0x8c, 0xfb,
	0x53, 0xd7, 0xaf, 0xfe, 0xf5, 0x17, 0xa2, 0x9c, 0x25, 0x3b, 0xc9, 0xea, 0x11, 0x7a, 0x03, 0x96,
	0xc6, 0x45, 0x5e, 0x6b, 0x48, 0xc6, 0xff, 0xa6, 0x83, 0xd3, 0xf0, 0x12, 0xdb, 0x81, 0xcc, 0xb6,
	0xf1, 0x8e, 0x55, 0x43, 0xa3, 0x67, 0x70, 0xce, 0xfb, 0xe6, 0x04, 0xcd, 0x93, 0xe2, 0xf7, 0x04,
	0xa3, 0xa9, 0x03, 0x24, 0xc3, 0xd5, 0x2d, 0x46, 0x32, 0x53, 0x29, 0xf4, 0xee, 0x30, 0xa2, 0x4c,
	0x95, 0x7b, 0xed, 0x63, 0x95, 0x8f, 0xbe, 0x09, 0xf4, 0x03, 0xa4, 0x9c, 0x67, 0x07, 0x91, 0xc8,
	0x5c, 0x20, 0x53, 0xca, 0xc3, 0x13, 0x53, 0xca, 0x43, 0xda, 0x87, 0x66, 0x7c, 0x40, 0x47, 0x87,
	0x35, 0xe3, 0x03, 0x75, 0xa1, 0xf5, 0x29, 0x4a, 0x34, 0x75, 0x98, 0x91, 0xf4, 0xee, 0x9c, 0xba,
	0x8d, 0xd4, 0x17, 0x27, 0x90, 0x20, 0xce, 0x23, 0xa1, 0xfe, 0x82, 0x5f, 0x43, 0x77, 0xaf, 0x85,
	0xfa, 0x30, 0x4e, 0x1d, 0x44, 0xaf, 0x73, 0xaa, 0x02, 0x66, 0xf6, 0xbe, 0x4e, 0x7a, 0xc3, 0x0b,
	0xee, 0x59, 0xc7, 0xab, 0x8c, 0x9e, 0x0c, 0xc0, 0xae, 0xf2, 0xa4, 0x00, 0xd6, 0x32, 0x60, 0x6f,
	0x2f, 0x2b, 0xb7, 0x31, 0xb9, 0x04, 0xa8, 0x17, 0xd2, 0xff, 0xd0, 0x9b, 0xcd, 0x97, 0xd3, 0x87,
	0xc7, 0x60, 0xc5, 0xdc, 0xc6, 0x53, 0xf7, 0xdd, 0x3a, 0xbe, 0xea, 0xda, 0xc2, 0x67, 0xbd, 0xff,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x9a, 0xb6, 0x37, 0xf6, 0x01, 0x00, 0x00,
}
